from .views import *
from .models import *
from rest_framework_simplejwt.views import TokenObtainPairView , TokenRefreshView
from rest_framework import routers
from Company_Details.views import  CompanyViewset,UserViewset,User_infoViewSet,DepartmentViewset,Hod_namesViewset,LocationsViewsets

router = routers.DefaultRouter()
router.register('Safety_Observations_Company',CompanyViewset)
router.register('Safety_Observations_User_Informations',User_infoViewSet,basename='Users')
router.register('Safety_Observations_Safety_Forms',Safety_FormsViewset)
router.register('Safety_Observations_Safety_Form_RP',Safety_Form_RPViewset)
router.register('Safety_Observations_Safety_Form_Others',Others_FormsViewset)
router.register('Safety_Observations_Safety_Form_PP',Safety_Form_PPViewset)
router.register('Safety_Observations_Safety_Form_PPE',Safety_Form_PPEViewset)
router.register('Safety_Observations_Safety_Form_TE',Safety_Form_TEViewset)
router.register('Safety_Observations_Safety_Form_PRO',Safety_Form_PROViewset)
router.register('Safety_Observations_Safety_Form_HK',Safety_Form_HKViewset)
router.register('Safety_Observations_Safety_Form_Safe_Situation',Safe_situationViewset)
router.register('Safety_Observations_User',UserViewset)
router.register('Safety_Observations_Location_names',LocationsViewsets)
router.register('Safety_Observations_Hod_names',Hod_namesViewset)
router.register('Safety_Observations_Sheduler',SchedulerViewset)
router.register('Safety_Observations_Shedules',SchedulesViewset,basename='Shedules')
router.register('Safety_Observations_Department',DepartmentViewset)
router.register('Safety_Observations_Open_Issues',OpenissuesViewset)
router.register('Safety_Observations_Closed_Issues',CloseissuesViewset)
router.register('Safety_Observations_Pending_Issues',PendingissuesViewset)
router.register('Safety_Observations_Open_Issues_count',OpenissuescountViewset)
router.register('Safety_Observations_Closed_Issues_count',CloseissuescountViewset)
router.register('Safety_Observations_Pending_Issues_count',PendingissuescountViewset)
router.register('Safety_Observations_Schedules_Users',Schedules_userViewset)
router.register('Safety_Observations_Get_Schedules',Get_SchedulesViewset)
router.register('Safety_Observations_Reschedule',RescheduleViewset)
router.register('Safety_Observations_Start_work',Start_workViewset)
router.register('Safety_Observations_Completed_works',Completed_worksViewset)
router.register('Safety_Observations_Completed_works_count',Total_observations_completedViewset)
router.register('Safety_Observations_Total_works_count',Total_observationsViewset)
router.register('Safety_Observations_Pending_works',Pending_worksViewset,basename='Schedules')
router.register('Safety_Observations_Safe_Situations_count',Safe_SituationsCount)
router.register('Safety_Observations_Safety_Forms_Agreed_Closes',Safety_Forms_Agreed_Closes)
router.register('Safety_Observations_Forward_issue',Forward_issueViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Get_Forward_issue',Get_Forward_issueViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Assign_Due_Date',Assign_Due_dateViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Closing_Request',Closing_RequestViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Get_Closing_Request',Get_Closing_RequestViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Close_Request',Close_RequestViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Overdue_Issues',OverdueissuesViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Overdue_Issues_Count',OverdueissuescountViewset,basename='Safety_Observation_Form')
#router.register('Closed_After_Action',Closed_AfteractionViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Closed_After_Action_Count',Closed_AfteractioncountViewset,basename='Safety_Observation_Form')
router.register('Safety_Observations_Hod_Notification',Hod_NotificationViewset)
router.register('Safety_Observations_Observer_Form_Notification',Observer_Form_NotificationViewset)
router.register('Safety_Observations_Observer_Next_Schedule_Notification',Observer_Next_Schedule_NotificationViewset)
router.register('Safety_Observations_Observer_Completed_Schedule_Notification',Observer_Completed_Schedule_NotificationViewset)
router.register('Safety_Observations_Observer_Missed_Schedule_Notification',Observer_Missed_Schedule_NotificationViewset)
router.register('Safety_Observations_Coordinator_New_Form_Notification',Coordinator_New_Form_NotificationViewset)
router.register('Safety_Observations_Coordinator_Due_Form_Notification',Coordinator_Due_Form_NotificationViewset)
router.register('Safety_Observations_Coordinator_Schedule_Missed_Notification',Coordinator_Schedule_Missed_NotificationViewset)
router.register('Safety_Observations_Coordinator_Schedule_Missed_Notification',Coordinator_Schedule_Missed_NotificationViewset)

