# Generated by Django 3.1.2 on 2020-11-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Safety_Observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safety_observation_form',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
