# Generated by Django 3.1.2 on 2020-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Safety_Observations', '0002_safety_observation_form_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifscation', models.CharField(max_length=100000)),
            ],
        ),
        migrations.AddField(
            model_name='schedules',
            name='reason_reschedule',
            field=models.TextField(null=True),
        ),
    ]
