# Generated by Django 3.1.2 on 2020-11-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Safety_Observations', '0003_auto_20201106_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifscation',
            new_name='notification',
        ),
    ]
